[package]
name = "rustfmt_if_chain"
version = "0.1.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "An if_chain-aware rustfmt (kind of)"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/smoelius/rustfmt_if_chain"
autoexamples = false

[dependencies]
anyhow = "1.0.52"
if_chain = "1.0.2"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
quote = "1.0.14"
sedregex = "0.2.5"
syn = { version = "1.0.84", features = ["full", "visit"] }
tempfile = "3.2.0"

[dev-dependencies]
assert_cmd = "2.0.2"
walkdir = "2.3.2"
