name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 2" # 2 = Tuesday
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers/
            ~/.rustup/toolchains/
            target/dylint/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          rm -f "$HOME"/.cargo/bin/cargo-fmt
          rm -f "$HOME"/.cargo/bin/rustfmt
          rustup install nightly
          rustup component add clippy --toolchain nightly
          rustup component add rustfmt
          rustup component add rustfmt --toolchain nightly
          cargo install cargo-dylint dylint-link || true
          cargo install cargo-license            || true
          cargo install cargo-sort               || true
          cargo install cargo-udeps              || true

      - name: Test
        run: cargo test --features=ci

      - name: Test with checks
        run: cargo +nightly test --features=all-checks
        env:
          CAST_CHECKS_LOG: 1
          RUSTFLAGS: --cfg procmacro2_semver_exempt
