name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 2" # 2 = Tuesday
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers/
            ~/.rustup/toolchains/
            target/dylint/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install tools
        run: |
          rm -f "$HOME"/.cargo/bin/cargo-fmt
          rm -f "$HOME"/.cargo/bin/rustfmt
          rustup update
          rustup install nightly
          rustup component add clippy --toolchain nightly
          rustup component add rustfmt
          rustup component add rustfmt --toolchain nightly
          cargo install cargo-dylint dylint-link || true
          cargo install cargo-license            || true
          cargo install cargo-sort               || true
          cargo install cargo-supply-chain       || true
          cargo install cargo-udeps              || true

      - name: Test
        run: cargo test --features=ci

      - name: Test with checks
        run: cargo test --features=rewriter/check-offsets,rewriter/check-rewrites
