name: Update supply chain

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # smoelius: The next use of `actions/cache` should match what is in ci.yml.
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers/
            ~/.rustup/toolchains/
            target/dylint/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-supply-chain
        run: cargo install cargo-supply-chain || true

      - name: Update supply_chain.json
        run: cargo test --features=ci --test ci supply_chain
        env:
          BLESS: 1

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update supply_chain.json"
          branch-suffix: random
